### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by apcraig**
## PR checklist
- [X] Short (1 sentence) summary of your PR: 
    Update documentation prior to merging to Consortium
- [X] Developer(s): 
    apcraig
- [X] Suggest PR reviewers from list in the column to the right.
- [X] Please copy the PR test results link or provide a summary of testing completed below.
    no testing done, changes only to documentation
- How much do the PR code changes differ from the unmodified code? 
    - [X] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on CICE or any other models?
    - [ ] Yes
    - [X] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [X] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/.)
    - [X] Yes
    - [ ] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [ ] No 
- [X] Please provide any additional information or relevant details below:

This primarily updates the Icepack public interfaces.  I checked the rest of the documentation, all new namelist and CPPs are already documented.  The shortwave changes on this branch are also documented.  Are there other things that are missing in the documentation?  Ultimately, this is trying to fix any missing documentation from this PR, https://github.com/CICE-Consortium/Icepack/pull/460

### CODE REVIEW

**Comment by apcraig** [comment]
I've activated this branch in readthedocs.  You can see the latest documentation associated with this PR here, https://apcraig-icepack.readthedocs.io/en/e3smdocs1/

**Review by eclare108213 — COMMENTED** [review]
Things to check/fix if needed :

- make sure Tf options are explained in the text
- hi_min - note in the PR that default might change answers in non-CESM configurations, but now it's a namelist option.  Add note about it in main text.
- Tliquidus_max - note in PR the original value and that it's now in namelist.  Add note about it in main text.

**Comment by apcraig** [comment]
I updated the PR about hi_min and Tliquidus_max.  I also took a shot at updating the documentation with additional info about Tf, hi_min, and Tliquidus_max.  But those might be wrong, please have a look and suggest other wording and especially if the changes belong in a different part of the user guide.

**Review by eclare108213 — APPROVED** [review]
Nice detective work!  This looks good to me.  Thank you.

**Pull request merged**
