### PR TITLE
Update Icepack z-biogeochemistry and z-aerosols with the MPAS-Sea ice column package 

### PR DESCRIPTION
**Pull request by njeffery**
## PR checklist
- [x] Short (1 sentence) summary of your PR: 
   Updates Icepack z-bgc and z-aerosols to the latest mpas-sea ice column package version
- [X] Developer(s): 
    Nicole Jeffery
- [X] Suggest PR reviewers from list in the column to the right.
- Elizabeth and Tony
- [X] Please copy the PR test results link or provide a summary of testing completed below.
    https://acme-climate.atlassian.net/wiki/spaces/ICE/pages/4225073188/icepack.GMPAS.EC30to60E2r2.BGC+and+GMPAS.EC30to60E2r2

- How much do the PR code changes differ from the unmodified code? 
    - [X] bit for bit  with bgc and z-aerosols off
    - [ ] different at roundoff level
    - [X] more substantial  with bgc on
- Does this PR create or have dependencies on CICE or any other models?
    - [ X] Yes - uses E3SM and a new interface
    - [ ] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [X] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/.)
    - [ ] Yes
    - [X] No, does the documentation need to be updated at a later time?
        - [X] Yes
        - [ ] No 
- [ ] Please provide any additional information or relevant details below:

ECH edited to fix checkboxes

### CODE REVIEW

**Comment by apcraig** [comment]
I don't think this is being merged to the correct place, E3SM-Project/Icepack/main should probably remain synced to Consortium/Icepack/main.  Should we merge this to Consortium Icepack main first?  Or to a branch on E3SM/Icepack?  Are there things in particular that needed to be reviewed, tested, refactored?  How should we proceed, maybe we should chat sometime.

**Comment by eclare108213** [comment]
This PR is showing all of the commits from the last 2 years, so the base code definitely needs to be resync'ed first.  Rebased?  @njeffery has been developing and testing in E3SM, so it makes sense to merge there then pull back to the Consortium, although our preference is to test and merge in the Consortium then PR to E3SM.  Either way, we'll need an iteration to resync the two repos, whether it's done as part of this PR or separately.  @njeffery is your origin code from E3SM's fork or from the Consortium?  `git remote -v`

**Comment by njeffery** [comment]
All those commits are because I merged my branch to @apcraig squash merge  (E3SM fork of Icpack commit 8fad768.

**Comment by apcraig** [comment]
I'm not clear on the history of the branch, but maybe it would be good to clarify and clean up if needed.  I know we could create a clean branch.  The best process depends how we're going to proceed.

Icepack in E3SM is a submodule.  If we want these mods to be added just to the E3SM version of Icepack, we need to create a "clean" branch in E3SM/Icepack based on the current E3SM version so the E3SM submodule can be updated.  We don't want to merge this to E3SM/Icepack/main (as the PR currently does).  We would probably test with Consortium/Icepack/main at the same time to make sure these mods work both in E3SM and in Consortium.

Alternatively, this could be merged into the Consortium/Icepack/main then E3SM/Icepack/main could be resynced and the E3SM Icepack submodule could be updated.  But E3SM would then get all the latest mods from the Consortium (although that's probably not a lot of stuff).  I think that's how we "planned" to do things wrt E3SM/Consortium.

So, those seem like the two main options (push to E3SM and Consortium separately or push to Consortium then use in E3SM).  In either case, I think we should test with both E3SM and within the Consortium (Icepack and CICE) before we finalize the PR.  But open to other ideas about how to best proceed.

**Comment by eclare108213** [comment]
The BGC updates went directly into E3SM via @njeffery's branch, then were merged into the CICE Consortium's repo which is now being resynced with E3SM.  Closing this PR.

**Pull request closed without merging**
