### PR TITLE
mpassi options files

### PR DESCRIPTION
**Pull request by eclare108213**
- [x] Short (1 sentence) summary of your PR: 
    Namelist and environment options for Icepack runs configured similarly to MPAS-SI single-column.
- [x] Developer(s): 
    @eclare108213 @njeffery @dabail10
- [x] Suggest PR reviewers from list in the column to the right.
- [ ] Please copy the PR test results link or provide a summary of testing completed below.
    ENTER INFORMATION HERE 
- How much do the PR code changes differ from the unmodified code?   NA
    - [ ] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on CICE or any other models?
    - [ ] Yes
    - [x] No
- Does this PR add any new test cases?
    - [x] Yes
    - [ ] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/.)
    - [ ] Yes
    - [x] No, does the documentation need to be updated at a later time?
        - [x] Yes, possibly
        - [ ] No 
- [x] Please provide any additional information or relevant details below:

Specifies namelist settings and the number of ice and snow layers, as agreed on for comparison runs between Icepack and MPAS-SI.  In particular (some of these values are already set as defaults in icepack_in):

- 7 ice layers (NICELYR)
- 5 snow layers (NSNWLYR)
- 5 ice thickness categories (NCAT)
- old ice thickness category boundaries, not round numbers (kcatbound=0)
- remap ice thickness distribution, not delta function (kitd=1)
- snow tracers are turned off, for now (tr_snow=.false.)
- dry snow grain radius = 1500 (rsnw_tmax)
- emissivity = 0.95
- ocean mixed layer is turned off (oceanmixed=.false.)

Variations on these tests can be created by turning on or adding other options files.

Example command for a test with snicar-ad off:
`./icepack.setup -m conda --env macos --case nmlst0 -s mpassi`

Example command for a test with snicar-ad on:
`./icepack.setup -m conda --env macos --case nmlst1 -s mpassi,snicar`

This PR is a draft until we decide on the final, default configuration, which might also require changes to forcing, etc.

### CODE REVIEW

**Comment by eclare108213** [comment]
@njeffery 
Is it possible to run the MPAS-SI column configuration with the ISPOL or NICE forcing?  We have that available in Icepack, and it might include enough atm/ocn data to make a reasonable test case for both models, also one we could use as we merge the BGC code.

**Comment by njeffery** [comment]
@eclare108213 
I should think so.  I'll look into using ISPOL/NICE.  Can you point me to this forcing?

**Comment by dabail10** [comment]
It can be obtained from here:

https://github.com/CICE-Consortium/Icepack/wiki/Icepack-Input-Data#description-of-tar-file

**Comment by dabail10** [comment]
Sorry, this has the Zenodo link:

https://github.com/CICE-Consortium/Icepack/wiki/Icepack-Input-Data

**Comment by njeffery** [comment]
@eclare108213 :  It'll take some effort to set up ISPOL/NICE forcing in mpas-si but I think worth it.  If you don't mind waiting a few weeks, I'll work on this when I have time.

**Review by njeffery — APPROVED** [review]
Verified that the Icepack_in options are consistent with  mpassi_in for agreed upon single-cell test.  

Note that the current mpassi single-cell test still needs namelist updates to conform.

**Comment by darincomeau** [comment]
Added an MPAS-Seaice testcase to match these config options here: https://github.com/MPAS-Dev/MPAS-Seaice_standalone_framework/pull/14

**Review by apcraig — APPROVED** [review]

**Comment by eclare108213** [comment]
Hmmm, wondering if this PR or branch (or whatever) wasn't named correctly according to E3SM's convention, or if it matters.  The component name is supposed to be included in the (which?) string?  What else?  Is this something we can fix when we finally PR the new Icepack code into E3SM?

**Comment by darincomeau** [comment]
I think the naming conventions only matter for PRs going directly into `E3SM-Project/E3SM` master? But here's the naming convention page for reference:
https://acme-climate.atlassian.net/wiki/spaces/DOC/pages/2523172/Branch+Tag+and+Version+name+conventions

**Pull request merged**
