### PR TITLE
Merge CICE-Consortium/Icepack main to E3SM-Project/Icepack main

### PR DESCRIPTION
**Pull request by apcraig**
This is a simple PR created directly from the repositories.

### CODE REVIEW

**Comment by eclare108213** [comment]
I am testing this using the E3SM-Polar-Developer script.

**Comment by eclare108213** [comment]
Running QC test on the following directories:
  /lcrc/group/e3sm/ac.eclare/E3SM-Polar/D12.qcbaseline.emc.qcbaseline20240413.master.E3SM-Project.anvil/run.k000/
  /lcrc/group/e3sm/ac.eclare/E3SM-Polar/D12.qcbaseline.emc.update_icepack_20240412.master.E3SM-Project.anvil/run.k000
Number of files: 61
2 Stage Test Passed
Quadratic Skill Test Passed for Northern Hemisphere
Quadratic Skill Test Passed for Southern Hemisphere

**Comment by eclare108213** [comment]
Baseline E3SM:

```
--- Global Energy and Mass Conservation for Month 03, Year 0001:

    relativeEnergyError:  	+1.78312e-03
    relativeMassError:  	+1.18320e-06
    relativeSaltError:  	-9.78900e-17
    relativeCarbonError:  	+0.00000e+00

--- Average Global Values for Month 03, Year 0001:

			North 			South
    1980-2022 Extent:	+1.530286800000000e+07 	+4.128757000000000e+06
    totalIceExtent	+1.629369209297351e+07 	+1.705213445957203e+07
    totalIceVolume	+3.636707252614450e+04 	+2.499332039374441e+04
    totalSnowVolume	+3.268645596762610e+03 	+7.460772897206572e+02
    totalKineticEnergy	+2.233036288084481e+14 	+3.397156886195364e+14
    averageAlbedo	+3.595186295033303e-01 	+1.763111566892719e-01

			Minimum 		Maximum
    iceAreaCell 	+0.000000000000000e+00 	+9.999938011169434e-01
    iceVolumeCell 	+0.000000000000000e+00 	+4.600533485412598e+00
    icePressure 	+0.000000000000000e+00 	+1.692133593750000e+05
    uVelocityGeo 	-4.285480380058289e-01 	+5.492014884948730e-01
    vVelocityGeo 	-4.407684504985809e-01 	+4.059779047966003e-01
```

E3SM with updated Icepack

```
--- Global Energy and Mass Conservation for Month 03, Year 0001:

    relativeEnergyError:  	+1.78396e-03
    relativeMassError:  	+1.17827e-06
    relativeSaltError:  	-2.80610e-16
    relativeCarbonError:  	+0.00000e+00

--- Average Global Values for Month 03, Year 0001:

			North 			South
    1980-2022 Extent:	+1.530286800000000e+07 	+4.128757000000000e+06
    totalIceExtent	+1.629368454672141e+07 	+1.705176894139234e+07
    totalIceVolume	+3.636728686167497e+04 	+2.499222023248838e+04
    totalSnowVolume	+3.268699112949644e+03 	+7.451200732825436e+02
    totalKineticEnergy	+2.233177964238433e+14 	+3.397029549194099e+14
    averageAlbedo	+3.595267401230673e-01 	+1.762149195049135e-01

			Minimum 		Maximum
    iceAreaCell 	+0.000000000000000e+00 	+9.999940395355225e-01
    iceVolumeCell 	+0.000000000000000e+00 	+4.600161075592041e+00
    icePressure 	+0.000000000000000e+00 	+1.691377031250000e+05
    uVelocityGeo 	-4.285481274127960e-01 	+5.492023229598999e-01
    vVelocityGeo 	-4.407695531845093e-01 	+4.059588909149170e-01
```

**Comment by eclare108213** [comment]
Here are the stats comparing the 5-year QC runs.

```
$ ./E3SM-Polar-Developer.sh -s qcbaseline20240413 -k qcbaseline.nlk -e -d60 -a D12.qcbaseline.emc.update_icepack_20240412.master.E3SM-Project.anvil -v

--- D-CASE AT STANDARD RESOLUTION WITH JRA 1.5 FORCING
    2000_DATM%JRA-1p5_SLND_MPASSI_DOCN%SOM_DROF%JRA-1p5_SGLC_SWAV_TEST, 
    TL319_EC30to60E2r2, S layout, 32 combos allowed

--- Fork origin is different from the default: git@github.com:E3SM-Project/E3SM.git
    Sandbox origin is: git@github.com:E3SM-Project/E3SM

--- Skipping clone of code ---

--- Reading combinations from D12.qcbaseline.emc.qcbaseline20240413.master.E3SM-Project.anvil/qcbaseline.nlk

    k000 ->
    mpassi: 	config_AM_thicknesses_write_on_startup = .true.
    mpassi: 	config_AM_thicknesses_compute_on_startup = .true.
    mpassi: 	config_AM_thicknesses_enable = .true.

--- Skipping create newcase ---

--- Skipping build for k000

--- Skipping queue for k000

--- Starting analysis ---

    All submissions out to 0006-01-01-00000 -
    run.D12.qcbaseline.emc.qcbaseline20240413.master.E3SM-Project.anvil.666565 k000: Complete
    run.D12.qcbaseline.emc.qcbaseline20240413.master.E3SM-Project.anvil.666571 k000: Complete
    run.D12.qcbaseline.emc.qcbaseline20240413.master.E3SM-Project.anvil.666573 k000: Complete
    run.D12.qcbaseline.emc.qcbaseline20240413.master.E3SM-Project.anvil.666578 k000: Complete
    run.D12.qcbaseline.emc.qcbaseline20240413.master.E3SM-Project.anvil.666579 k000: Complete

    All submissions out to 0006-01-01-00000 -
    run.D12.qcbaseline.emc.update_icepack_20240412.master.E3SM-Project.anvil.666560 k000: Complete
    run.D12.qcbaseline.emc.update_icepack_20240412.master.E3SM-Project.anvil.666564 k000: Complete
    run.D12.qcbaseline.emc.update_icepack_20240412.master.E3SM-Project.anvil.666570 k000: Complete
    run.D12.qcbaseline.emc.update_icepack_20240412.master.E3SM-Project.anvil.666572 k000: Complete
    run.D12.qcbaseline.emc.update_icepack_20240412.master.E3SM-Project.anvil.666577 k000: Complete

--- Global Energy and Mass Conservation for Month 12, Year 0005:

    D12.qcbaseline.emc.qcbaseline20240413.master.E3SM-Project.anvil k000:

    relativeEnergyError:  	+4.59932e-03
    relativeMassError:  	+1.67645e-07
    relativeSaltError:  	-1.13700e-16
    relativeCarbonError:  	+0.00000e+00

    D12.qcbaseline.emc.update_icepack_20240412.master.E3SM-Project.anvil k000:

    relativeEnergyError:  	+4.60260e-03
    relativeMassError:  	+1.66784e-07
    relativeSaltError:  	-1.39900e-17
    relativeCarbonError:  	+0.00000e+00

--- Average Differences for Month 12, Year 0005:

    D12.qcbaseline.emc.qcbaseline20240413.master.E3SM-Project.anvil k000 - 
    D12.qcbaseline.emc.update_icepack_20240412.master.E3SM-Project.anvil k000:

			Minimum 	Maximum
    iceAreaCell 	-1.20475e-02 	+2.77486e-02
    iceVolumeCell 	-1.50131e-01 	+1.31364e-01
    icePressure 	-7.12052e+03 	+5.06067e+03
    uVelocityGeo 	-1.68541e-02 	+4.32362e-02
    vVelocityGeo 	-8.97751e-03 	+1.82618e-02

			North 		South
    totalIceExtent 	+3.39529e+02 	+6.57685e+03
    totalIceVolume 	+1.20362e+01 	+2.85916e+00
    totalSnowVolume 	+3.82790e+00 	-1.41116e+00
    totalKineticEnergy 	+5.55519e+11 	+1.73564e+10
    averageAlbedo 	+6.49974e-07 	+8.84199e-05

--- Case root: /lcrc/group/e3sm/ac.eclare/E3SM-Polar/
    D12.qcbaseline.emc.qcbaseline20240413.master.E3SM-Project.anvil

--- Code root: ~/E3SM-Polar/code/qcbaseline20240413

--- Provenance root: ~/E3SM-Polar/provenance/qcbaseline20240413/
    D12.qcbaseline.emc.qcbaseline20240413.master.E3SM-Project.anvil

--- Script saved: E3SM-Polar-Developer.sh.20240415-113612
```

**Review by proteanplanet — COMMENTED** [review]
We have worked further on the high resolution version of E3SM and determined that the model is also crashing with a data sea ice model, thereby eliminating anything in this PR as a potential cause of model instability.  In consultation with the HR team and with @eclare108213, I would like to suggest we close this PR so as not to complicate @njeffery 's work that would automatically see this change brought into E3SM as part of the BGC tag.

**Comment by eclare108213** [comment]
The contents of this PR will likely NOT be brought in with @njeffery's BGC mods.  I think it's best to keep them separate, since they are both somewhat large collections of changes and their intent is different.  The argument for not merging this PR yet is so that it's easier to compare Nicole's code / simulations to existing fully coupled (water cycle) runs.  If the control runs will not be BFB due to other changes/bug fixes, then I we could go ahead with this PR. Then @njeffery would need to rebase and retest -- that's extra work that we'd prefer to avoid.  Are non-BFB changes going into master now?

**Comment by apcraig** [comment]
Also, there really isn't any risk/cost to merge this.  If the plan is to keep the E3SM-Project/Icepack main synced up with the Consortium/Icepack main, this PR is just doing that.  We could probably create a github action that would do it automatically once a week and it would have no impact on any other development or plans.   Merging this PR has no impact on the bgc branch or whether bgc is updated to the current main.  That is a totally independent step.  It also has no impact on the Icepack hash that E3SM points to.  That hash can be on any branch.  At some points, it could be a hash from main, but never has to be.  All that assumes the plan is for the E3SM-Project/Icepack main to match the Consortium/Icepack main exactly always and for that update to happen periodically.

**Comment by eclare108213** [comment]
That's true, E3SM will not point to this new hash. But I think this branch (main) is where we had planned to force-push changes from the Consortium in order to keep the history clean, so I don't think we would actually merge this PR anyhow.  Mostly I don't want to confuse the order in which things happen, relative to the BGC merge.  If we're going to make these changes in E3SM first, then let's do it following the established process, which I think means force-pushing to E3SM Icepack main and then opening another PR into E3SM itself, linking the new Icepack hash, and moving the documentation above into that PR.  But that's harder for Nicole to deal with, so I'm waiting.  It's good to know that my tests above succeeded cleanly.  I do not know whether Rob et al will want us to update the Icepack link in E3SM separately for the resync and for the BGC, or if we could PR them together - my guess is that they'll need to be done separately.

**Comment by apcraig** [comment]
I'm not sure I understand the plan.  The current E3SM Icepack main is up to date with Consortium from a few months ago.  I think we forced pushed then, so the history is identical, just E3SM is a bit behind.  This PR just does this push from Consortium main to E3SM main, we don't need to force push, just don't squash merge and the mains will remain synced up with identical history.  That is taken care of with this PR.  As I said, we could probably automate this merge weekly if we wanted, don't need to force push as long as nobody pushed onto E3SM main when they shouldn't.

For bgc, we may want or have to fix the history, but that would NOT have to happen from the head of main and what's on main wouldn't matter.  We would find the appropriate hash to branch from on main (or elsewhere), create a branch from it, then merge the bgc changes onto it.  When bgc is ready, the hash on that branch would be used in E3SM and then could be merged to Consortium main.  We cannot and should not require the head of main in E3SM to be somehow associated with some current version of Icepack that's useful in E3SM.  There may be hashes on main that are particularly useful wrt E3SM development, we can know/discover what those are quite easily.  But the head of main should not be part of the equation of that.

We should never be force pushing again in general.  Only if someone commits something to main that shouldn't be there.  We should probably clarify the process again, seems like there is some confusion.

**Comment by eclare108213** [comment]
Okay, we need to sort through this. It's is already on the agenda for the Icepack meeting tomorrow:  https://acme-climate.atlassian.net/wiki/spaces/ICE/pages/4254990453/2024-04-17+Icepack+Merge+Meeting+notes

**Review by eclare108213 — APPROVED** [review]
This version of Icepack has been thoroughly tested in the CICE Consortium's test suites and released as v1.5.0.  It will be tested further in E3SM from this fork, prior to a PR into E3SM.

**Pull request merged**
