### PR TITLE
Update to Icepack1.3.3 release, #8f96707, Dec 9, 2022

### PR DESCRIPTION
**Pull request by apcraig**
## PR checklist
- [X] Short (1 sentence) summary of your PR: 
    Update to Icepack1.3.3 release, #8f96707, Dec 9, 2022.
- [X] Developer(s): 
    apcraig
- [X] Suggest PR reviewers from list in the column to the right.
- [X] Please copy the PR test results link or provide a summary of testing completed below.
    bit-for-bit with Consortium main #8f96707 except modal tests, https://github.com/CICE-Consortium/Test-Results/wiki/icepack_by_hash_forks#9d083558fefc1326bff6438015157ca53dbea956.  Testing with CICE E3SMIcepackDEV looks good, https://github.com/CICE-Consortium/Test-Results/wiki/cice_by_hash_forks#ec8632ff210525aa1569048ea80e7fb647b811d6.  log files are identical, restart files change in Tsfc at non-ice points (expected).
- How much do the PR code changes differ from the unmodified code? 
    - [X] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on CICE or any other models?
    - [ ] Yes
    - [X] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [X] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/.)
    - [X] Yes
    - [ ] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [ ] No 
- [ ] Please provide any additional information or relevant details below:

### CODE REVIEW

**Review by eclare108213 — APPROVED** [review]

**Comment by eclare108213** [comment]
Thanks @apcraig.  Let me know when your CICE E3SMIcepackDEV are done, and I'll merge this.  I'd like to update the E3SM fork to point to this one soon, so that the saltflux changes are in there as we begin to implement and test thermo etc.

**Comment by apcraig** [comment]
CICE testing is all good, https://github.com/CICE-Consortium/Test-Results/wiki/cice_by_hash_forks#ec8632ff210525aa1569048ea80e7fb647b811d6.  Will create a PR for CICE E3SMIcepackDEV shortly.

This is ready to merge.

**Comment by eclare108213** [comment]
Great, thank you.  I will merge @darincomeau's PR to our E3SM fork/branch before pointing it to this new version of icepack.

**Comment by apcraig** [comment]
If you can merge this when you have a chance, then I can create the PR for CICE E3SMIcepackDEV.  Thanks.

**Pull request merged**
